# ConfigData
---
eureka:
  client:
    serviceUrl: 
      #defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      defaultZone: http://localhost:8010/eureka/
# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog 
